modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="the_cubed_gallifreyan"
version="1.0.0"
displayName="The Cubed Gallifreyan"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Jordan Arruda, MCreator"

[[dependencies.the_cubed_gallifreyan]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




